name: Build
on: [push]
jobs:
  Build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository Contents
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm ci
          npm run build
