name: Lint
on: [pull_request]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Copying repository content
        uses: actions/checkout@v1

      - name: eslint
        run: |
          npm ci
          npm run lint:es

  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Copying repository content
        uses: actions/checkout@v1

      - name: stylelint
        run: |
          npm ci
          npm run lint:style
